(()=>{
  // Keep these records in the same local state and backup as the rest of Guàrdia.
  if(!Array.isArray(state.detentions))state.detentions=[];
  const $d=id=>document.getElementById(id),form=$d('detentionForm');let year=policeYear(new Date()),editing=null;
  const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(new Date(value+'T00:00:00').getTime());
  const safeRows=()=>state.detentions.filter(r=>r&&validDate(r.date)&&Number.isInteger(Number(r.count))&&Number(r.count)>0);
  const personsFor=targetYear=>safeRows().filter(r=>policeYear(new Date(r.date+'T12:00:00'))===targetYear).reduce((sum,r)=>sum+Number(r.count),0);
  function setFeedback(text,error=false){let el=$d('detentionFeedback');el.textContent=text;el.hidden=!text;el.classList.toggle('error',error)}
  function renderTotals(){let rows=safeRows().filter(r=>policeYear(new Date(r.date+'T12:00:00'))===selectedYear);$d('summaryDetentions').textContent=rows.reduce((sum,r)=>sum+Number(r.count),0).toLocaleString('ca')}
  function render(){let rows=safeRows().filter(r=>policeYear(new Date(r.date+'T12:00:00'))===year).sort((a,b)=>b.date.localeCompare(a.date));$d('detentionYear').textContent=year+'–'+(year+1);$d('detentionPeople').textContent=personsFor(year).toLocaleString('ca');$d('detentionCases').textContent=rows.length.toLocaleString('ca');let list=$d('detentionList');list.replaceChildren();if(!rows.length){let empty=document.createElement('p');empty.className='detention-empty';empty.textContent='Encara no hi ha registres en aquest any policial.';list.append(empty)}for(let item of rows){let article=document.createElement('article');article.className='detention-item';let content=document.createElement('div');let title=document.createElement('h4');title.textContent=displayDate(item.date)+' · '+item.count+' '+(Number(item.count)===1?'detingut':'detinguts');content.append(title);for(let [label,value] of [['Diligències',item.proceedings],['Concepte',item.concept],['TIP dels agents',(item.tips||[]).join(', ')],['Dades dels detinguts',item.personDetails],['Text',item.note]]){if(!value)continue;let p=document.createElement('p');p.textContent=label+': '+value;content.append(p)}let edit=document.createElement('button');edit.type='button';edit.textContent='Editar';edit.setAttribute('aria-label','Editar registre del '+displayDate(item.date));edit.onclick=()=>open(item);article.append(content,edit);list.append(article)}renderTotals()}
  function open(item=null){editing=item?.id||null;form.reset();form.elements.date.value=item?.date||new Date().toLocaleDateString('sv-SE');form.elements.proceedings.value=item?.proceedings||'';form.elements.concept.value=item?.concept||'';form.elements.count.value=item?.count||1;form.elements.tips.value=(item?.tips||[state.profile?.tip].filter(Boolean)).join(', ');form.elements.personDetails.value=item?.personDetails||'';form.elements.note.value=item?.note||'';$d('detentionFormTitle').textContent=item?'Editar registre':'Nou registre';$d('deleteDetention').hidden=!item;form.hidden=false;setFeedback('');form.scrollIntoView({behavior:'smooth',block:'start'})}
  $d('newDetention').onclick=()=>open();$d('cancelDetention').onclick=()=>{form.hidden=true;editing=null;setFeedback('')};
  for(let id of ['detentionPrev','detentionNext'])$d(id).onclick=()=>{year+=id==='detentionPrev'?-1:1;render()};
  $d('detentionPlus').onclick=()=>{form.elements.count.value=Math.min(99,(Number(form.elements.count.value)||0)+1)};
  $d('detentionMinus').onclick=()=>{form.elements.count.value=Math.max(1,(Number(form.elements.count.value)||1)-1)};
  form.onsubmit=e=>{e.preventDefault();let values=form.elements,date=values.date.value,count=Number(values.count.value),tips=values.tips.value.trim()?values.tips.value.trim().split(/[\s,;]+/).filter(Boolean):[];if(!validDate(date)||date>new Date().toLocaleDateString('sv-SE')||!Number.isInteger(count)||count<1||count>99){setFeedback('Revisa la data i el nombre de detinguts (d’1 a 99).',true);return}if(tips.length>8||tips.some(tip=>!/^\d{1,10}$/.test(tip))){setFeedback('Introdueix fins a 8 TIP numèrics, separats per comes.',true);return}let item={id:editing||crypto.randomUUID(),date,proceedings:values.proceedings.value.trim(),concept:values.concept.value.trim(),count,tips,personDetails:values.personDetails.value.trim(),note:values.note.value.trim()},old=state.detentions.slice(),index=state.detentions.findIndex(r=>r.id===editing);if(index>=0)state.detentions[index]=item;else state.detentions.push(item);if(!save()){state.detentions=old;setFeedback('No s’ha pogut desar el registre.',true);return}year=policeYear(new Date(date+'T12:00:00'));render();form.hidden=true;editing=null;setFeedback('✓ Registre desat correctament.')};
  $d('deleteDetention').onclick=()=>{if(!editing||!confirm('Eliminar aquest registre de detinguts?'))return;let old=state.detentions.slice();state.detentions=state.detentions.filter(r=>r.id!==editing);if(!save()){state.detentions=old;setFeedback('No s’ha pogut eliminar el registre.',true);return}render();form.hidden=true;editing=null;setFeedback('✓ Registre eliminat.')};
  document.querySelector('[data-screen="detentions"]').addEventListener('click',render);
  // Totals changes police year independently of this screen.
  for(let id of ['summaryPrev','summaryNext','yearPrev','yearNext'])$d(id)?.addEventListener('click',renderTotals);
  render();
})();
