/* Control del CEV per especial responsabilitat. Imports i tarifes guardats per registre. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id),root=$('responsibility');if(!root)return;
  const ranks={mosso:'Mosso / Agent',caporal:'Caporal',sergent:'Sergent',sotsinspector:'Sotsinspector'};
  const pairs={mosso:{caporal:253,sergent:504},caporal:{sergent:253},sergent:{sotsinspector:253}};
  if(!Array.isArray(state.responsibilityEntries))state.responsibilityEntries=[];
  state.responsibilityRates ||= {2026:{'mosso:caporal':253,'mosso:sergent':504,'caporal:sergent':253,'sergent:sotsinspector':253}};
  let month=key(new Date()).slice(0,7),draft=[],editingId=null,draftPair='',paymentId=null;
  const cents=row=>Math.round(row.minutes*row.rateCents/60),amount=rows=>rows.reduce((sum,row)=>sum+cents(row),0);
  const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')&&Number.isFinite(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
  const node=(tag,text,className)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e};
  root.innerHTML=`<div class="panel"><div class="toolbar"><h3>Responsabilitat</h3><div class="month"><button type="button" id="respPrev" aria-label="Mes anterior">‹</button><input type="month" id="respMonth" aria-label="Mes de consulta"><button type="button" id="respNext" aria-label="Mes següent">›</button></div></div><p class="sub">Complement específic variable per especial responsabilitat.</p><div class="stats resp-stats"><div class="card"><small>Hores registrades</small><strong id="respTotalHours">0 h</strong></div><div class="card"><small>Import calculat</small><strong id="respTotal">0 €</strong></div><div class="card money-unpaid"><small>Pendent de cobrar</small><strong id="respPending">0 €</strong></div><div class="card money-paid"><small>Cobrat</small><strong id="respPaid">0 €</strong></div></div><div id="respList" class="resp-list"></div></div>
  <div class="panel resp-editor"><h3 id="respEditorTitle">Afegir responsabilitat</h3><form id="respForm" class="form"><label>El teu grau<select id="respOwn" required><option value="">Tria el grau</option><option value="mosso">Mosso / Agent</option><option value="caporal">Caporal</option><option value="sergent">Sergent</option></select></label><label>Responsabilitat assumida<select id="respTarget" required></select></label><label>Des del dia<input type="date" id="respStart" required></label><label>Fins al dia<input type="date" id="respEnd" required></label><label class="wide">Observacions (opcional)<input id="respNote" maxlength="180" placeholder="Servei o funcions assumides"></label><button type="submit">Preparar dies</button><button type="button" id="respCancelEdit" hidden>Cancel·lar edició</button></form><p class="sub">Revisa les hores efectivament assumides. Les hores del calendari són una proposta; els permisos es resten de les hores proposades.</p><div id="respDraft" class="resp-draft"></div><button type="button" class="primary" id="respSave" hidden>Desar registres</button><p id="respFeedback" role="status" aria-live="polite"></p></div>
  <details class="panel resp-rates"><summary>Tarifes per any</summary><p class="sub">Tarifes de referència 2026 facilitades. Els registres desats conserven la seva tarifa. Introdueix les tarifes dels altres anys abans de registrar-los.</p><form id="respRatesForm" class="form"><label>Any<input type="number" id="respRateYear" min="2020" max="2100" value="2026" required></label><div id="respRateFields" class="wide resp-rate-fields"></div><button type="submit" class="primary">Desar tarifes</button></form><p id="respRateFeedback" role="status"></p></details>
  <dialog id="respPaymentDialog"><h3>Marcar com a cobrat</h3><form id="respPaymentForm"><label>Mes de la nòmina<input type="month" id="respPayrollMonth" required></label><div class="resp-actions"><button type="submit" class="primary">Desar cobrament</button><button type="button" id="respPaymentCancel">Cancel·lar</button></div><p id="respPaymentFeedback" role="status"></p></form></dialog>`;
  $('respMonth').value=month;
  function feedback(text){$('respFeedback').textContent=text}
  function clearDraft(){draft=[];draftPair='';$('respDraft').replaceChildren();$('respSave').hidden=true;feedback('')}
  function targets(){const prior=$('respTarget').value;$('respTarget').replaceChildren();for(const value of Object.keys(pairs[$('respOwn').value]||{})){const o=node('option',ranks[value]);o.value=value;$('respTarget').append(o)}if([...$('respTarget').options].some(o=>o.value===prior))$('respTarget').value=prior;clearDraft()}
  function resetEditor(){editingId=null;clearDraft();$('respEditorTitle').textContent='Afegir responsabilitat';$('respCancelEdit').hidden=true;$('respOwn').value=pairs[state.profile.category]?state.profile.category:'';targets();$('respStart').value=key(new Date());$('respEnd').value=key(new Date());$('respNote').value=''}
  function calendarMinutes(date){if(state.leave[date]&&!combinableLeave.has(state.leave[date].category))return 0;const hours=shiftTypesForDate(date).reduce((sum,t)=>sum+duration(t),0);return Math.max(0,Math.round((hours-(Number(state.leave[date]?.hours)||0))*60))}
  function prepareRows(start,end,own,target){
    if(!validDate(start)||!validDate(end)||start>end||!pairs[own]?.[target])return {error:'Tria el grau, la responsabilitat i un interval vàlid.'};
    const first=Date.parse(start+'T00:00:00Z'),last=Date.parse(end+'T00:00:00Z');if((last-first)/86400000>365)return {error:'L’interval pot contenir com a màxim 366 dies.'};
    const rows=[];for(let ms=first;ms<=last;ms+=86400000){const date=new Date(ms).toISOString().slice(0,10),minutes=calendarMinutes(date);rows.push({date,minutes,rateCents:state.responsibilityRates[date.slice(0,4)]?.[own+':'+target],selected:minutes>0})}return {rows};
  }
  function drawDraft(){const list=$('respDraft');list.replaceChildren();for(const row of draft){const line=node('div',undefined,'resp-draft-row'),choose=node('input');choose.type='checkbox';choose.checked=row.selected;choose.setAttribute('aria-label','Incloure '+displayDate(row.date));choose.onchange=()=>row.selected=choose.checked;const day=node('strong',displayDate(row.date));const hoursLabel=node('label','Hores'),hours=node('input');hours.type='text';hours.inputMode='decimal';hours.value=hoursValue(row.minutes/60);hours.setAttribute('aria-label','Hores del '+displayDate(row.date));const rateLabel=node('label','€/hora'),rate=node('input');rate.type='number';rate.min='0';rate.max='10000';rate.step='0.01';rate.value=Number.isInteger(row.rateCents)?(row.rateCents/100).toFixed(2):'';rate.setAttribute('aria-label','Tarifa del '+displayDate(row.date));const total=node('strong');const update=()=>{const h=parseHours(hours.value),r=rate.value.trim()===''?NaN:Number(rate.value);row.minutes=Number.isFinite(h)?Math.round(h*60):NaN;row.rateCents=Number.isFinite(r)?Math.round(r*100):NaN;total.textContent=Number.isFinite(row.minutes)&&Number.isFinite(row.rateCents)?money(cents(row)/100):'Tarifa pendent'};hours.oninput=rate.oninput=update;update();hoursLabel.append(hours);rateLabel.append(rate);line.append(choose,day,hoursLabel,rateLabel,total);list.append(line)}$('respSave').hidden=!draft.length}
  $('respForm').onsubmit=e=>{e.preventDefault();const own=$('respOwn').value,target=$('respTarget').value,result=prepareRows($('respStart').value,$('respEnd').value,own,target);if(result.error){feedback(result.error);return}draft=result.rows;draftPair=own+':'+target;if(editingId){const old=state.responsibilityEntries.find(r=>r.id===editingId);if(old&&draft.length===1){draft[0].minutes=old.minutes;draft[0].rateCents=old.rateCents;draft[0].selected=true}}drawDraft();feedback('Revisa els dies marcats, les hores i les tarifes abans de desar.')};
  $('respOwn').onchange=targets;$('respTarget').onchange=clearDraft;for(const id of ['respStart','respEnd'])$(id).onchange=clearDraft;
  $('respCancelEdit').onclick=resetEditor;
  $('respSave').onclick=()=>{
    const rows=draft.filter(r=>r.selected),[own,target]=draftPair.split(':');if(!rows.length){feedback('Marca almenys un dia.');return}
    if(rows.some(r=>!Number.isInteger(r.minutes)||r.minutes<=0||r.minutes>1440||!Number.isInteger(r.rateCents)||r.rateCents<0||r.rateCents>1000000)){feedback('Revisa les hores (màxim 24 h per dia) i les tarifes.');return}
    const previous=state.responsibilityEntries,others=previous.filter(r=>r.id!==editingId);
    const duplicate=rows.find(r=>others.some(old=>old.date===r.date&&old.own===own&&old.target===target));if(duplicate){feedback('Ja hi ha aquesta responsabilitat el '+displayDate(duplicate.date)+'. Edita el registre existent.');return}
    if(editingId&&rows.length!==1){feedback('Per editar un registre, selecciona només un dia.');return}
    const old=previous.find(r=>r.id===editingId);state.responsibilityEntries=[...others,...rows.map(r=>({id:editingId||crypto.randomUUID(),date:r.date,own,target,minutes:r.minutes,rateCents:r.rateCents,note:$('respNote').value.trim(),paid:old?.paid||false,payrollMonth:old?.payrollMonth||''}))];
    if(!save()){state.responsibilityEntries=previous;feedback('No s’ha pogut desar. Torna-ho a provar.');return}
    month=rows[0].date.slice(0,7);$('respMonth').value=month;resetEditor();renderList();feedback('✓ Registres desats.');
  };
  function edit(row){editingId=row.id;$('respOwn').value=row.own;targets();$('respTarget').value=row.target;$('respStart').value=$('respEnd').value=row.date;$('respNote').value=row.note||'';$('respEditorTitle').textContent='Editar responsabilitat · '+displayDate(row.date);$('respCancelEdit').hidden=false;draft=[{date:row.date,minutes:row.minutes,rateCents:row.rateCents,selected:true}];draftPair=row.own+':'+row.target;drawDraft();$('respEditorTitle').scrollIntoView({behavior:'smooth',block:'center'})}
  function persistChange(update){const previous=state.responsibilityEntries;state.responsibilityEntries=update(previous);if(!save()){state.responsibilityEntries=previous;feedback('No s’ha pogut desar el canvi.');return false}renderList();return true}
  function renderList(){const rows=state.responsibilityEntries.filter(r=>r.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date));$('respTotalHours').textContent=hoursText(rows.reduce((sum,r)=>sum+r.minutes,0)/60);$('respTotal').textContent=money(amount(rows)/100);$('respPending').textContent=money(amount(rows.filter(r=>!r.paid))/100);$('respPaid').textContent=money(amount(rows.filter(r=>r.paid))/100);const list=$('respList');list.replaceChildren();if(!rows.length)list.append(node('p','Cap responsabilitat registrada aquest mes.','sub'));for(const row of rows){const article=node('article',undefined,'resp-row'),info=node('div'),title=node('strong',displayDate(row.date)+' · '+ranks[row.own]+' → '+ranks[row.target]);info.append(title,node('p',hoursText(row.minutes/60)+' × '+money(row.rateCents/100)+'/h = '+money(cents(row)/100)),node('p',row.paid?'Cobrat · nòmina '+row.payrollMonth:'Pendent de cobrar',row.paid?'resp-paid':'resp-pending'));if(row.note)info.append(node('p',row.note,'sub'));const actions=node('div',undefined,'resp-actions'),editButton=node('button','Editar'),remove=node('button','Eliminar'),paid=node('button',row.paid?'Tornar pendent':'Marcar cobrat');for(const b of [editButton,remove,paid])b.type='button';editButton.onclick=()=>edit(row);remove.onclick=()=>{if(confirm('Eliminar la responsabilitat del '+displayDate(row.date)+'?')){if(persistChange(items=>items.filter(r=>r.id!==row.id))&&editingId===row.id)resetEditor()}};paid.onclick=()=>{if(row.paid){persistChange(items=>items.map(r=>r.id===row.id?{...r,paid:false,payrollMonth:''}:r));return}paymentId=row.id;$('respPayrollMonth').value=key(new Date()).slice(0,7);$('respPaymentFeedback').textContent='';$('respPaymentDialog').showModal()};actions.append(editButton,paid,remove);article.append(info,actions);list.append(article)}}
  $('respPaymentCancel').onclick=()=>$('respPaymentDialog').close();$('respPaymentForm').onsubmit=e=>{e.preventDefault();const payrollMonth=$('respPayrollMonth').value;if(!/^\d{4}-\d{2}$/.test(payrollMonth))return;if(persistChange(items=>items.map(r=>r.id===paymentId?{...r,paid:true,payrollMonth}:r)))$('respPaymentDialog').close();else $('respPaymentFeedback').textContent='No s’ha pogut desar el cobrament.'};
  $('respMonth').onchange=()=>{if(/^\d{4}-\d{2}$/.test($('respMonth').value)){month=$('respMonth').value;renderList()}};
  function moveMonth(n){const [y,m]=month.split('-').map(Number);month=new Date(Date.UTC(y,m-1+n,1)).toISOString().slice(0,7);$('respMonth').value=month;renderList()}
  $('respPrev').onclick=()=>moveMonth(-1);$('respNext').onclick=()=>moveMonth(1);
  function drawRates(){const year=$('respRateYear').value,list=$('respRateFields');list.replaceChildren();for(const [own,targets] of Object.entries(pairs))for(const target of Object.keys(targets)){const label=node('label',ranks[own]+' → '+ranks[target]+' · €/h'),input=node('input');input.type='number';input.min='0';input.max='10000';input.step='0.01';input.required=true;input.dataset.pair=own+':'+target;const rate=state.responsibilityRates[year]?.[input.dataset.pair];input.value=Number.isInteger(rate)?(rate/100).toFixed(2):'';label.append(input);list.append(label)}}
  $('respRateYear').onchange=()=>{drawRates();$('respRateFeedback').textContent=''};
  $('respRatesForm').onsubmit=e=>{e.preventDefault();const year=Number($('respRateYear').value);if(!Number.isInteger(year)||year<2020||year>2100)return;const rates={};for(const input of $('respRateFields').querySelectorAll('input')){const n=Number(input.value);if(input.value===''||!Number.isFinite(n)||n<0||n>10000)return;rates[input.dataset.pair]=Math.round(n*100)}const before=state.responsibilityRates;state.responsibilityRates={...before,[year]:rates};if(!save()){state.responsibilityRates=before;$('respRateFeedback').textContent='No s’han pogut desar les tarifes.';return}$('respRateFeedback').textContent='✓ Tarifes desades. Els registres existents conserven la seva tarifa.'};
  window.GuardiaResponsibility={refresh(){if(!draft.length&&!editingId){const category=state.profile.category;$('respOwn').value=pairs[category]?category:'';targets()}renderList()}};
  resetEditor();drawRates();renderList();
})();
